### ISSUE TITLE
RtdClockVB-ExcelRtdServer not loading in VS

### ISSUE THREAD

**Issue by johnnyontheweb** [Excel-DNA/Samples#22]
Hello,
I tried to open RtdClockVB-ExcelRtdServer.sln in VS 2019, but VS tells me that "the project is not supported":

RtdClockVB-ExcelRtdServer.vbproj: Impossibile trovare l'applicazione su cui si basa questo tipo di progetto. Per ulteriori informazioni, provare a utilizzare il collegamento seguente: http://go.microsoft.com/fwlink/?LinkID=299083&projecttype=7c62086f-14b6-45f0-a11b-31698fd43e99
--

In English it would be, more or less, "Cannot find application on which this project is based"

**Comment by govert** [comment]
You can try to remove this line from the project file:

```
    <ProjectTypeGuids>{7c62086f-14b6-45f0-a11b-31698fd43e99};{F184B08F-C81C-45F6-A57F-5ABD9991F28F}</ProjectTypeGuids>
```

**Comment by johnnyontheweb** [comment]
thanks, it worked!
